import streamlit
streamlit.title('My Parents New Healthy Diner')
streamlit.header('Breakfast Menu')
streamlit.text('🫓Appam & Egg Curry')
streamlit.text('🥖Puttu & Kadala')
streamlit.text('🍪Porotta & Beef')
streamlit.text('🥑Omega 3 & Blueberry Oatmeal')
streamlit.text('🥬Kale, Spinach & Rocket Smoothie')
streamlit.text('🍇🍌Hard-Boiled Free-Range Egg')
streamlit.header('🍇🥑🥝🍇🍈🍉🍎🥭Build Your Own Good Smoothie🍍🍌🍋🍊🍏🍐🍑🍒🍓🫐')
